### ISSUE TITLE
Optional versus Result versus generics versus sum types

### ISSUE THREAD

**Issue by dumblob** [MaisaMilena/learning-time#1]
Perhaps a clear concise description of how these can advantageously interact is in https://github.com/vlang/rfcs/pull/7 .

**Comment by MaisaMilena** [comment]
hey, @dumblob ! I plan to study more and talk about Generics and Algebraic Data Types (sum, products). A comparison between all of them is still a big challenge for me, some day I get there. And thanks for the reference in `V Lang`

**Comment by dumblob** [comment]
I'm looking forward to the comparison (with examples?)! If you'll write the comparison in English, I'll definitelly read it :wink:.

Closing for lack of actionable items.
